# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WlDhaOaRZNMcQDR4tZLJW2EbPaLch_H0
"""

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from konlpy.tag import Okt

# --- 0. 페이지 기본 설정 ---
st.set_page_config(page_title="영주 Now AI 가이드", page_icon="🍔", layout="wide")

st.title(" 🚀 영주시 공공데이터 기반 AI 하이브리드 맛집 추천 엔진")
st.markdown("사용자의 구체적인 **상황(Context)**을 분석하여 가장 부합하는 영주 맛집 및 안심식당을 추천합니다.")

# --- 1. 데이터 로드 및 캐싱 (매번 새로 로드하지 않도록 방지) ---
@st.cache_data
def load_data():
    df = pd.read_csv("master_db.csv", encoding="utf-8")
    return df

df = load_data()
okt = Okt()

# --- 2. 자연어 처리 및 추천 알고리즘 함수 ---
def get_recommendations(user_input, df):
    # 형태소 분석 (명사, 형용사 추출)
    def tokenize(text):
        tokens = okt.pos(text, stem=True)
        return [word for word, pos in tokens if pos in ['Noun', 'Adjective']]

    # 식당 설명문 전처리
    df['clean_desc'] = df['description'].apply(lambda x: " ".join(tokenize(x)))
    user_clean = " ".join(tokenize(user_input))

    if not user_clean:
        return pd.DataFrame()

    # TF-IDF 벡터화 및 코사인 유사도 계산
    vectorizer = TfidfVectorizer()
    tfidf_matrix = vectorizer.fit_transform(df['clean_desc'])
    user_vector = vectorizer.transform([user_clean])

    sim_scores = cosine_similarity(user_vector, tfidf_matrix).flatten()

    # 하이브리드 스코어링 (코사인 유사도 + 안심식당 가중치 0.2)
    final_scores = sim_scores + (df['is_safe'] * 0.2)

    df['추천 점수'] = final_scores
    return df.sort_values(by='추천 점수', ascending=False).head(3)

# --- 3. 웹 UI 레이아웃 구성 ---
# 왼쪽 사이드바: 상황 입력창
with st.sidebar:
    st.header("🔍 상황 입력창")
    user_situation = st.text_input(
        "어떤 식당을 찾으시나요?",
        placeholder="예: 부모님 모시고 갈 조용한 한정식 맛집"
    )
    search_button = st.button("AI 추천 시작")

# 오른쪽 메인 화면: 결과 출력
if search_button and user_situation:
    with st.spinner("AI가 영주시 공공데이터를 융합하여 분석 중입니다..."):
        results = get_recommendations(user_situation, df)

        if results.empty:
            st.warning("입력하신 상황과 매칭되는 식당을 찾지 못했습니다. 다른 키워드로 입력해 보세요!")
        else:
            st.subheader("🎯 AI 선정 TOP 3 추천 결과")

            # 2단 레이아웃 (좌측: 카드 형태의 정보, 우측: 지도)
            col1, col2 = st.columns([1, 1])

            with col1:
                for idx, row in results.iterrows():
                    safe_badge = "✅ 안심식당" if row['is_safe'] == 1 else "❌ 일반식당"
                    st.info(f"### **{row['상호명']}** ({safe_badge})")
                    st.write(f"📍 **주소:** {row['주소']}")
                    st.write(f"📝 **특징:** {row['description']}")
                    st.write(f"📊 **매칭 점수:** {row['추천 점수']:.2f}")
                    st.write("---")

            with col2:
                st.markdown("### 🗺️ 추천 식당 위치")
                # 위도, 경도 컬럼명을 가진 데이터프레임을 주면 Streamlit이 자동으로 지도를 그려줍니다!
                map_data = results[['latitude', 'longitude']]
                st.map(map_data)
else:
    st.info("왼쪽 사이드바에 원하는 상황을 입력하고 버튼을 눌러보세요! 지도가 자동으로 연동됩니다.")
